spring:
#  r2dbc:
#    url: r2dbc:mysql://localhost:3306/employee_db
#    username: root
#    password: root
  application:
    name: EMPLOYEE-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://127.0.0.1:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      circuitBreakers:
        enabled: true
      show-details: always
      enabled: true
    tracing:
      sampling:
        probability: 1.0

  logging:
    pattern:
      level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    level:
      org:
        springframework:
          web: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        failoverRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permitNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org:
      springframework:
        web: DEBUG

#server:
#  port: 8081
#
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#      department-service:
#        name: department-service
#
#eureka:
#  instance:
#    client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka/